### ISSUE TITLE
Test issue notifications

### ISSUE THREAD

**Issue by lfarenw** [cposc/cposc-2014#1]
Wondering, how do you start a new "issue" and inform everyone? Rely on their notification settings? Do timely messages need to also be sent via email?

**Comment by jdmumper** [comment]
FWIW - I got this one...

## 

Jay Mumper
jdmumper@gmail.com
Google Voice: 717-469-5050
profile: https://www.google.com/+JayMumper

**Comment by lfarenw** [comment]
Okay, interesting. Do you have email notification set on for ALL repos that you watch, @jdmumper ? I didn't see a way to change those settings per-repo.

**Comment by lmarburger** [comment]
I have notifications enabled for all repositories I'm watching so I got this one too. I think we can rely on notification settings for general messages.

**Comment by jdmumper** [comment]
I actually did nothing but setup my account as a default user.  I haven't
actually done anything on GitHub as yet.  You subscribed me today and I
started getting stuff...

## 

Jay Mumper
jdmumper@gmail.com
Google Voice: 717-469-5050
profile: https://www.google.com/+JayMumper

**Comment by pearcec** [comment]
Got it.  This seems like a workable approach.

On Tue, Nov 19, 2013 at 10:21 AM, jdmumper notifications@github.com wrote:

> I actually did nothing but setup my account as a default user. I haven't
> actually done anything on GitHub as yet. You subscribed me today and I
> started getting stuff...
> 
> ## 
> 
> Jay Mumper
> jdmumper@gmail.com
> Google Voice: 717-469-5050
> profile: https://www.google.com/+JayMumper
> 
> On Tue, Nov 19, 2013 at 10:15 AM, Larry Marburger
> notifications@github.comwrote:
> 
> > I have notifications enabled for all repositories I'm watching so I got
> > this one too. I think we can rely on notification settings for general
> > messages.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/cposc/cposc-2014/issues/1#issuecomment-28797675>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cposc/cposc-2014/issues/1#issuecomment-28798291
> .

## 

Christian
