### ISSUE TITLE
Single track for last talk.

### ISSUE THREAD

**Issue by pearcec** [cposc/cposc-2014#3]
Just came back from Philly ETE 2014.  I was chatting up @lmarburger.  I was debating sticking around for the last talk of the day.  It is a common desire to leave early and get back part of your day, beat traffic, or whatever.  I ended up sticking around.

I was commenting on how we tried to keep the most interested talks for last to encourage attendance.  One reason for doing this is so there is an audience for the speakers.  Larry had a great idea.  Why not just go single track on the last talk.  Sure it lowers the number of total talks, but it gives the final speaker the similar size audience.

I thought it was a good idea so I didn't want to lose track of it.

**Comment by lfarenw** [comment]
An interesting idea. Was there anything particular about the last session
that encouraged you to stick around, other than the fact that it was single
track? Topic?

**Comment by pearcec** [comment]
Actually it wasn't single track.  We just discussed the idea.  I basically
wanted to get as much value as I could out of my time down there.  The talk
was on Spark it turned out to be awesome.

On Thu, Apr 24, 2014 at 8:42 AM, Lon Farenwald notifications@github.comwrote:

> An interesting idea. Was there anything particular about the last session
> that encouraged you to stick around, other than the fact that it was
> single
> track? Topic?
> 
> On Wed, Apr 23, 2014 at 8:17 PM, Christian Pearce
> notifications@github.comwrote:
> 
> > Just came back from Philly ETE 2014. I was chatting up @lmarburger<
> > https://github.com/lmarburger>.
> > I was debating sticking around for the last talk of the day. It is a
> > common
> > desire to leave early and get back part of your day, beat traffic, or
> > whatever. I ended up sticking around.
> > 
> > I was commenting on how we tried to keep the most interested talks for
> > last to encourage attendance. One reason for doing this is so there is
> > an
> > audience for the speakers. Larry had a great idea. Why not just go
> > single
> > track on the last talk. Sure it lowers the number of total talks, but it
> > gives the final speaker the similar size audience.
> > 
> > I thought it was a good idea so I didn't want to lose track of it.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/cposc/cposc-2014/issues/3>
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cposc/cposc-2014/issues/3#issuecomment-41274969
> .

## 

Christian

**Comment by alibby** [comment]
I like the idea.

Andy

On 4/25/14 6:40 PM, Christian Pearce wrote:

> Actually it wasn't single track. We just discussed the idea.
> I basically
> wanted to get as much value as I could out of my time down
> there. The talk
> was on Spark it turned out to be awesome.
> 
> On Thu, Apr 24, 2014 at 8:42 AM, Lon Farenwald
> notifications@github.comwrote:
> 
> > An interesting idea. Was there anything particular about
> > the last session
> > that encouraged you to stick around, other than the fact
> > that it was
> > single
> > track? Topic?
> > 
> > On Wed, Apr 23, 2014 at 8:17 PM, Christian Pearce
> > notifications@github.comwrote:
> > 
> > > Just came back from Philly ETE 2014. I was chatting up
> > > @lmarburger<
> > > https://github.com/lmarburger>.
> > > I was debating sticking around for the last talk of the
> > > day. It is a
> > > common
> > > desire to leave early and get back part of your day,
> > > beat traffic, or
> > > whatever. I ended up sticking around.
> > > 
> > > I was commenting on how we tried to keep the most
> > > interested talks for
> > > last to encourage attendance. One reason for doing this
> > > is so there is
> > > an
> > > audience for the speakers. Larry had a great idea. Why
> > > not just go
> > > single
> > > track on the last talk. Sure it lowers the number of
> > > total talks, but it
> > > gives the final speaker the similar size audience.
> > > 
> > > I thought it was a good idea so I didn't want to lose
> > > track of it.
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/cposc/cposc-2014/issues/3>
> > > .
> > 
> > ## 
> > 
> > Reply to this email directly or view it on
> > GitHubhttps://github.com/cposc/cposc-2014/issues/3#issuecomment-41274969
> > .
> 
> ## 
> 
> Christian
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cposc/cposc-2014/issues/3#issuecomment-41446314.

## 

Andrew Libby
xforty technologies
http://xforty.com
http://zugunroute.com
alibby@xforty.com
484-887-7505 x 1115

**Comment by jdmumper** [comment]
I think we might even want to post the last talk as a "keynote" - perhaps
with someone who is a particularly well-known.  For example, we had talked
about pinging Eric Raymond to appear at CPOSC. Eric is kind of quirky, but
might be a draw.

I don't know him personally, but I do know that Jim Capp had several
conversations with Eric way back when I was part of the newly created
Anteil and we were heading for a possible IPO.  I'm not sure if Jim has
maintained any contact, but I can ask...

## 

Jay Mumper
jdmumper@gmail.com
Google Voice: 717-469-5050
profile: https://www.google.com/+JayMumper
