### ISSUE TITLE
Date Reserved

### ISSUE THREAD

**Issue by lfarenw** [cposc/cposc-2014#5]
Talked to IU13 and the Nov 1st date has been reserved for us. Still have some paperwork to fill out for them, but it's on the calendar!

**Comment by tjj814** [comment]
Thanks

Sent from Yahoo Mail on Android

**Comment by alibby** [comment]
Nice!

**Comment by jdmumper** [comment]
Great. Now the real work of organizing the whole event starts ;)

## 

Jay Mumper
jdmumper@gmail.com
Google Voice: 717-469-5050
profile: https://www.google.com/+JayMumper
